#! @Chapter Introduction
#!
#! @Section Comenzando con QGNAG
#!
#! Este paquete posee un conjuntos funciones que se complementan
#! con el paquete GBNP y permiten realizar cómputos de Grupos
#! Cuánticos de Grupos No Abelianos, denotados como
#! $\mathcal{D}(\mathfrak{B}(V)\#\Bbbk G)$ donde $G$ es un grupo finito no
#! abeliano y $\mathfrak{B}(V)$ es un álgebra de Nichols de dimensión
#! finita sobre $\mathbb{Q}$.
#!
#! @Subsection Instalación
#!
#! Para instalar este paquete, consulte las instrucciones de instalación en
#! el archivo README del código fuente. Se encuentra aquí:
#! <URL>https://github.com/juniors90/QGNAG/blob/master/README.md</URL>.
#!
#! @Subsection A quantum group at a non-abelian group
#!
#! A lo largo de esta documentación, fijamos un grupo no abeliano
#! finito <A>G</A> o $G$ y un módulo Yetter-Drinfeld
#! $V \in {}_G^G\mathcal{YD}$ tal que su álgebra de Nichols
#! $\mathcal{B}(V)$ es de dimensión finita.
#! Denotamos por $\mathfrak{D}$ el doble de Drinfled de la bosonización
#! $\mathcal{B}(V) \# \Bbbk G$. Para abreviar, decimos que
#! $\mathbf{D}$ es un grupo cuántico en un grupo no abeliano.
#! 
#! En la primera parte de la sección, describimos la estructura
#! algebraica de $\mathbf{D}$. Luego introducimos y estudiamos
#! los módulos de Verma para $\mathfrak{D}$.
#!
#! @Chapter A quantum group at a non-abelian group
#!
#! Quantum groups arising from semisimple Lie algebras and their
#! finite-dimensional analogues have played a central role in modern
#! representation theory. Their importance stems not only from their
#! intrinsic algebraic structure but also from the rich category of
#! representations they admit.
#!
#! One of the fundamental observations in the theory is that many
#! representation-theoretic properties are consequences of the existence
#! of a triangular decomposition.
#!
#! Let <M>U</M> denote either the universal enveloping algebra of a
#! semisimple Lie algebra or a quantum group associated with a Cartan
#! datum. In both situations one has distinguished subalgebras
#! <M>U^{-}</M>, <M>U^{0}</M> and <M>U^{+}</M> such that the multiplication
#! map induces a vector space isomorphism
#! <Display>
#! U^{-}\otimes U^{0}\otimes U^{+}
#! \longrightarrow U.
#! </Display>
#! The commutative Hopf algebra <M>U^{0}</M> determines a notion of
#! weight, while the positive and negative parts control the structure
#! of highest-weight modules and Verma modules.
#!
#! Let
#! <Display>
#! T=\operatorname{Specm}(U^{0})
#! </Display>
#! denote the maximal spectrum of <M>U^{0}</M>.
#! The elements of <M>T</M> are called weights.
#! If <M>\lambda\in T</M>, the corresponding one-dimensional module is
#! denoted by <M>k_{\lambda}</M>.
#!
#! The tensor product of one-dimensional weight modules reflects the
#! group structure of <M>T</M>:
#! <Display>
#! k_{\lambda}\otimes k_{\mu}
#! \simeq
#! k_{\lambda+\mu}.
#! </Display>
#! If <M>M</M> is a <M>U</M>-module, its weight space of weight
#! <M>\lambda</M> is
#! <Display>
#! M_{\lambda}
#! =
#! \{
#! m\in M
#! \;:\;
#! h\cdot m=\lambda(h)m
#! \text{ for all }
#! h\in U^{0}
#! \}.
#! </Display>
#! The decomposition of a module into weight spaces is one of the
#! principal tools in the representation theory of Lie algebras and
#! quantum groups.
#!
#! A highest-weight module of highest weight <M>\lambda</M> is a module
#! generated by a vector
#! <M>v\in M_{\lambda}</M>
#! satisfying
#! <Display>
#! U^{+}v=0.
#! </Display>
#! The most important examples are the Verma modules
#! <Display>
#! M(\lambda)
#! =
#! U\otimes_{U^{\ge 0}}k_{\lambda},
#! </Display>
#! where
#! <Display>
#! U^{\ge 0}
#! =
#! \langle U^{0},U^{+}\rangle .
#! </Display>
#! Verma modules occupy a distinguished position because every simple
#! highest-weight module arises from them.
#!
#! More precisely:
#! <List>
#! <Item>
#! Every Verma module possesses a unique simple quotient.
#! </Item>
#! <Item>
#! Every simple highest-weight module is the quotient of a unique Verma
#! module.
#! </Item>
#! <Item>
#! Every Verma module is a free <M>U^{-}</M>-module of rank one.
#! </Item>
#! </List>
#! These facts form the foundation of highest-weight theory.
#!
#! The purpose of the work of Pogorelsky and Vay <Cite Key="pogorelsky2016verma"/>
#! was to develop an analogous framework for a family of finite-dimensional Hopf algebras
#! associated with finite non-abelian groups.
#!
#! Let <M>G</M> be a finite group and let <M>V</M> be a
#! Yetter-Drinfeld module over <M>kG</M> whose Nichols algebra
#! <M>\mathfrak{B}(V)</M> is finite-dimensional.
#!
#! The Drinfeld double of the bosonization
#! <M>
#! \mathfrak{B}(V)\#kG
#! </M>
#! gives rise to a finite-dimensional Hopf algebra
#! <M>
#! \mathfrak{D}.
#! </M>. Following Pogorelsky and Vay, this algebra is called a
#! quantum group at a non-abelian group.
#!
#! These Hopf algebras generalize the quantum groups associated with
#! semisimple Lie algebras and provide a setting in which many ideas from
#! highest-weight theory survive despite the absence of a Cartan
#! subalgebra.
#!
#! A key observation is that
#! <M>\mathfrak{D}</M>
#! admits a triangular decomposition
#! <Display>
#! \mathfrak{D}
#! \cong
#! \mathfrak{B}(V)
#! \otimes
#! \mathcal{D}(G)
#! \otimes
#! \mathfrak{B}(\overline{V}),
#! </Display>
#!
#! where
#! <M>\mathcal{D}(G)</M>
#! denotes the Drinfeld double of the group algebra
#! <M>\Bbbk G</M>.
#!
#! The algebra
#! <M>\mathcal{D}(G)</M>
#! replaces the role played by the Cartan part
#! <M>U^{0}</M>
#! in classical highest-weight theory.
#!
#! Unlike the Cartan algebra of a semisimple Lie algebra,
#! <M>\mathcal{D}(G)</M>
#! is semisimple but generally noncommutative.
#! Consequently, weights are no longer indexed by characters of an
#! abelian group.
#!
#! The simple
#! <M>\mathcal{D}(G)</M>-modules
#! are parametrized by pairs
#! <M>
#! (\mathcal O,\rho),
#! </M>
#! where
#! <M>\mathcal O</M>
#! is a conjugacy class of
#! <M>G</M>
#! and
#! <M>\rho</M>
#! is an irreducible representation of the centralizer of a fixed
#! element of
#! <M>\mathcal O</M>.
#!
#! If
#! <M>M(g,\rho)</M>
#! denotes the corresponding simple
#! <M>\mathcal{D}(G)</M>-module,
#! then it can be regarded as a module over
#! <M>\mathfrak{D}^{\ge 0}</M>
#! by letting
#! <M>\mathfrak{B}(\overline V)</M>
#! act trivially.
#!
#! This leads naturally to the definition of the Verma module
#! <Display>
#! \mathsf{M}(g,\rho)
#! =
#! \mathfrak{D}
#! \otimes_{\mathfrak{D}^{\ge 0}}
#! M(g,\rho).
#! </Display>
#!
#! These modules play the same role as ordinary Verma modules in Lie
#! theory.
#!
#! One of the principal results of Pogorelsky and Vay asserts that every
#! Verma module possesses a unique simple quotient and every simple
#! <M>\mathfrak{D}</M>-module arises as the quotient of a unique Verma
#! module.
#!
#! Consequently there is a bijection
#! <Display>
#! \{
#! \text{simple }
#! \mathcal{D}(G)\text{-modules}
#! \}
#! \longleftrightarrow
#! \{
#! \text{simple }
#! \mathfrak{D}\text{-modules}
#! \}.
#! </Display>
#! If
#! <M>\mathsf{L}(g,\rho)</M>
#! denotes the head of
#! <M>\mathsf M(g,\rho)</M>,
#! then the correspondence is given by
#! <Display>
#! M(g,\rho)
#! \longmapsto
#! \mathsf{L}(g,\rho).
#! </Display>
#! Furthermore, the socle of a Verma module is also simple and yields a
#! second parametrization of the simple modules.
#!
#! The algebra
#! <M>\mathfrak{D}</M>
#! inherits a natural
#! <M>\mathbb{Z}</M>-grading from the Nichols algebras.
#! Explicitly,
#! <Display>
#! \mathfrak{D}^{n}
#! =
#! \bigoplus_{n=j-i}
#! \mathfrak{B}^{i}(V)
#! \otimes
#! \mathcal{D}(G)
#! \otimes
#! \mathfrak{B}^{j}(\overline V).
#! </Display>
#! This grading plays a fundamental role in both the theoretical and
#! computational aspects of the representation theory.
#!
#! The package <Package>QGNAG</Package> is devoted to the explicit study of these quantum
#! groups and their representations.
#!
#! The algorithms implemented in the package exploit the triangular
#! decomposition, the grading of Nichols algebras, and the highest-weight
#! theory of Verma modules in order to construct and analyze modules
#! through explicit matrix computations.
#!
#! In particular, <Package>QGNAG</Package> provides tools for constructing Verma modules,
#! computing graded bases, determining homogeneous actions, studying
#! socles and heads, computing spaces of homomorphisms, and investigating
#! the structure of simple modules.
#!
#! The package is intended both as a computational framework for
#! experimentation and as a research tool for the representation theory
#! of quantum groups at non-abelian groups.
#!
#! @Chapter Preliminaries
#!
#! @Section Base Conventions
#!
#! Throughout this work, $\Bbbk$ denotes an algebraically closed field of characteristic zero.
#! The dual of a vector space $V$ is denoted by $V^*$.
#! For $v \in V$ and $f \in V^*$, we write $\langle f, v \rangle$ for the evaluation of $f$ at $v$.
#!
#! Let $S$ be a set. We denote by $\Bbbk S$ the free vector space generated by $S$.
#! If $A$ is an algebra, an $A$-module always means a left $A$-module.
#! If $S \subseteq M$ is a subset of an $A$-module $M$ and $B \subseteq A$, we write
#! $$
#! BS = \{ bs \mid b \in B,\ s \in S \}.
#! $$
#!
#! @Section Hopf Algebras
#!
#! Let $H$ be a finite-dimensional Hopf algebra over $\Bbbk$.
#! We denote by $\Delta$, $\mathcal{S}$ and $\varepsilon$ the comultiplication,
#! antipode and counit of $H$, respectively.
#!
#! We use Sweedler notation:
#! $$
#! \Delta(h) = h_{(1)} \otimes h_{(2)}, \quad h \in H.
#! $$
#! For a right $H$-comodule $M$, we write:
#! $$
#! \delta(m) = m_{(-1)} \otimes m_{(0)}, \quad m \in M.
#! $$
#!
#! @Section Yetter-Drinfeld Modules
#!
#! The category ${}_H^H\mathcal{YD}$ denotes the category of Yetter-Drinfeld modules over $H$.
#! Its objects are $H$-modules and $H$-comodules $M$ satisfying the compatibility condition:
#! $$
#! (hm)_{(-1)} \otimes (hm)_{(0)}
#! =
#! h_{(1)} m_{(-1)} \mathcal{S}(h_{(3)}) \otimes h_{(2)} m_{(0)},
#! $$
#! for all $h \in H$ and $m \in M$.
#!
#! @Section Drinfeld Double
#!
#! @Subsection Construction
#!
#! We consider the Drinfeld double $\mathfrak{D}(H)$ of $H$.
#! As a coalgebra, it is given by:
#! $$
#! \mathfrak{D}(H) = H \otimes H^*.
#! $$
#!
#! The multiplication is defined by:
#! $$
#! (h \otimes f)(h' \otimes f')
#! =
#! \langle f_{(1)}, h'_{(1)} \rangle
#! \langle f_{(3)}, \mathcal{S}_H(h'_{(3)}) \rangle
#! (h h'_{(2)} \otimes f' f_{(2)}),
#! $$
#! for all $h,h' \in H$, $f,f' \in H^*$.
#!
#! The antipode is given by:
#! $$
#! \mathcal{S}(h \otimes f)
#! =
#! (1 \otimes \mathcal{S}_{H^*}^{-1}(f))
#! (\mathcal{S}_H(h) \otimes \varepsilon).
#! $$
#!
#! In particular, $H$ and $H^{*op}$ embed as Hopf subalgebras of $\mathfrak{D}(H)$.
#!
#! @Subsection Module Interpretation
#!
#! The category ${}_H^H\mathcal{YD}$ is braided equivalent to the category of
#! $\mathfrak{D}(H)$-modules, denoted ${}_{\mathfrak{D}(H)}\mathcal{M}$.
#!
#! Explicitly, if $M \in {}_H^H\mathcal{YD}$, then $M$ becomes a
#! $\mathfrak{D}(H)$-module via:
#! $$
#! (h f)\cdot m = \langle f, m_{(-1)} \rangle\, h m_{(0)},
#! $$
#! for all $h \in H$, $f \in H^*$, $m \in M$.
#!
#! @Section Nichols Algebras

#! @Subsection Construction of Nichols Algebras
#!
#! Let $H$ be a Hopf algebra and let $V \in {}^H_H\mathcal{YD}$ be a Yetter-Drinfeld module.
#! The Nichols algebra of $V$ is constructed as follows (see for instance [2, §2.1]).
#!
#! We first consider the tensor algebra $T(V)$, viewed as a graded braided Hopf algebra in
#! ${}^H_H\mathcal{YD}$, with structure maps defined on generators $v \in V$ by:
#! $$
#! \Delta(v) = v \otimes 1 + 1 \otimes v, \quad
#! \mathcal{S}(v) = -v, \quad
#! \varepsilon(v) = 0.
#! $$
#!
#! Let $\mathfrak{J}(V)$ be the maximal homogeneous ideal and coideal of $T(V)$ generated by all
#! elements of degree $\geq 2$.
#!
#! The Nichols algebra of $V$ is defined as the quotient:
#! $$
#! \mathfrak{B}(V) = T(V) / \mathfrak{J}(V).
#! $$
#!
#! It is a graded braided Hopf algebra in ${}^H_H\mathcal{YD}$.
#! Its homogeneous component of degree $n \in \mathbb{N}$ is denoted by $\mathfrak{B}^n(V)$.
#!
#! We have:
#! $$
#! \mathfrak{B}^1(V) = V, \quad \mathfrak{B}^0(V) = \Bbbk.
#! $$
#!
#! If $\mathfrak{B}(V)$ is finite-dimensional, then its top homogeneous component is
#! one-dimensional and coincides with the space of left and right integrals
#! (see [1, §§2.3 and 3.2]).
#!
#! @Subsection Bosonization
#!
#! The bosonization $\mathfrak{B}(V)\#H$ is the Hopf algebra introduced in [15,11].
#! It is defined on the vector space:
#! $$
#! \mathfrak{B}(V) \otimes H,
#! $$
#! with Hopf algebra structure determined by requiring that:
#!
#! - $H$ is a Hopf subalgebra,
#! - $\mathfrak{B}(V)$ is a subalgebra,
#! - and for all $h \in H$, $v \in V$, the cross relation holds: $$h v = (h_{(1)} \cdot v)\# h_{(2)}.$$
#! The comultiplication on generators $v \in V$ is given by:
#! $$
#! \Delta(v) = v \otimes 1 + v_{(-1)} \otimes v_{(0)}.
#! $$
#! The bosonization is a graded Hopf algebra with grading:
#! $$
#! (\mathfrak{B}(V)\#H)^n = \mathfrak{B}^n(V)\#H,
#! \quad n \in \mathbb{N}.
#! $$
#!
#! @Section Dual Group Algebra and Gradings
#!
#! @Subsection Dual Group Algebra
#!
#! Let $G$ be a finite group with unit element denoted by $e$.
#!
#! We consider the dual Hopf algebra:
#! $$
#! \Bbbk^G := (\Bbbk G)^*,
#! $$
#! where $\Bbbk G$ is the group algebra of $G$.
#!
#! Let $\{ \delta_g \}_{g \in G}$ be the dual basis of the canonical basis
#! $\{ g \}_{g \in G}$ of $\Bbbk G$.
#!
#! The comultiplication is given by:
#! $$
#! \Delta(\delta_g) = \sum_{t \in G} \delta_t \otimes \delta_{t^{-1} g}.
#! $$
#!

#! @Subsection Graded Structure of $\Bbbk^G$-Modules
#!
#! Let $M$ be a $\Bbbk^G$-module and let $g \in G$.
#! Then $M$ admits a natural $G$-grading with homogeneous components:
#! $$
#! M[g] = \delta_g M
#! = \{ m \in M \mid f \cdot m = f(g)m,\ \forall f \in \Bbbk^G \}.
#! $$
#!
#! If $S \subseteq M$, we define:
#! $$
#! S[g] := S \cap M[g].
#! $$
#!
#! The support of $M$ is defined as:
#! $$
#! \operatorname{Supp}(M)
#! :=
#! \{ g \in G \mid M[g] \neq 0 \}.
#! $$
#!
#! The one-dimensional $\Bbbk^G$-module concentrated in degree $g \in G$
#! is denoted by $\Bbbk_g$.
#!
#! @Subsection Adjoint Action on Algebras
#!
#! Let $A$ be an algebra containing $\Bbbk^G$ as a subalgebra.
#! Then $A$ is regarded as a $\Bbbk^G$-module via the adjoint action:
#! $$
#! f \cdot a = \operatorname{ad}(f)(a)
#! := f_{(1)} a \mathcal{S}(f_{(2)}),
#! $$
#! for all $f \in \Bbbk^G$ and $a \in A$.

#! @Section Drinfeld Double of a Group Algebra
#!
#! @Subsection Structure of $\mathfrak{D}(G)$
#!
#! Let $G$ be a finite group and let $\Bbbk G$ be its group algebra.
#! We denote by $\mathfrak{D}(G)$ the Drinfeld double of $\Bbbk G$.
#!
#! Since $\Bbbk^G$ is a commutative Hopf algebra, both $\Bbbk^G$ and $\Bbbk G$
#! embed as Hopf subalgebras of $\mathfrak{D}(G)$.
#!
#! The algebra structure of $\mathfrak{D}(G)$ is determined by the cross relation:
#! $$
#! \delta_h g = g \delta_{g^{-1} h g},
#! \quad \forall g,h \in G.
#! $$
#!

#! @Subsection Simple Modules and Classification
#!
#! Simple $\mathfrak{D}(G)$-modules correspond to simple objects in
#! ${}_{\Bbbk G}^{\Bbbk G}\mathcal{YD}$.
#! A complete description can be found in [1, §3.1].
#!
#! We recall this classification in the language of $\mathfrak{D}(G)$-modules.
#!
#! Let $\mathcal{O}_g$ be the conjugacy class of $g \in G$ and
#! let $\mathcal{C}_g$ denote its centralizer.
#!
#! Let $(U, \varrho)$ be an irreducible representation of $\mathcal{C}_g$.
#!

#! @Subsection Induced Modules
#!
#! The induced $\Bbbk G$-module associated to $(U, \varrho)$ is defined by:
#! $$
#! M(g, \varrho)
#! :=
#! \operatorname{Ind}_{\mathcal{C}_g}^G U
#! =
#! \Bbbk G \otimes_{\Bbbk \mathcal{C}_g} U.
#! $$
#!
#! This space becomes a $\Bbbk^G$-module via:
#! $$
#! f \cdot (x \otimes u)
#! =
#! \langle f, x g x^{-1} \rangle (x \otimes u),
#! $$
#! for all $f \in \Bbbk^G$, $x \in G$, $u \in U$.
#!
#! Consequently, the element $x \otimes u$ has $G$-degree $x g x^{-1}$.
#!
#! The support satisfies:
#! $$
#! \operatorname{Supp}(M(g,\varrho)) = \mathcal{O}_g.
#! $$
#!
#! Moreover:
#! $$
#! \dim M(g,\varrho) = |\mathcal{O}_g| \cdot \dim U.
#! $$
#!
#! The module $M(g,\varrho)$ extends uniquely to a $\mathfrak{D}(G)$-module.
#!
#! Furthermore, $M(g,\varrho)$ is simple, and every simple
#! $\mathfrak{D}(G)$-module arises in this way (see [1, Prop. 3.1.2]).
#!
#! @Subsection Weight Modules
#!
#! 
#! A $\mathfrak{D}(G)$-module is said to be of weight $(g,\varrho)$
#! if it is isomorphic to $M(g,\varrho)$.
#! 
#!
#! @Chapter Elements of Semidirect Product
#!
#! @Chapter Elements of Tensor Product
#!
#! @Chapter Basis for Yetter-Drinfeld module
#!
#! @Chapter Quantum Groups and Bicrossproduct Structures
#!
#! @Chapter Nichols Smash Products
#!
#! @Chapter Nichols algebras attached to affine racks
#!
#! @Chapter Elements of <M>\mathbb{F}\textsubscript{4}</M>
#!
#! @Chapter Structure Matrices for Actions on Nichols Algebras
#!
#! @Chapter Precomputed Rewriting Data
#!
#! @Chapter Utilities
#! 