#! @Chapter Nichols algebras attached to affine racks
#!
#! @Section Relations of <M>kG^\ast</M>
#!
#! @Arguments yIndex
#!
#! @Returns A list of relations defining the algebra generated by the indices in <A>yIndex</A>.
#!
#! @Description
#!
#! Constructs the defining relations associated to the dual group
#! algebra
#! <M>kG^\ast</M>.
#!
#! The argument <A>yIndex</A> is a list of indices representing the
#! generators corresponding to delta functions
#! <M>\delta_g</M>.
#!
#! The function produces relations encoding:
#! <List>
#!   <Item>
#!     orthogonality of distinct delta functions;
#!   </Item>
#!   <Item>
#!     idempotency of each delta function;
#!   </Item>
#!   <Item>
#!     the partition of unity relation.
#!   </Item>
#! </List>
#!
#! More precisely:
#! <List>
#!   <Item>
#!     if
#!     <M>i \neq j</M>,
#!     the relation
#!     <M>\delta_i\delta_j = 0</M>
#!     is encoded by
#!     <M>[ [ [i,j] ], [1] ]</M>;
#!   </Item>
#!   <Item>
#!     if
#!     <M>i=j</M>,
#!     the idempotent relation
#!     <M>\delta_i^2-\delta_i=0</M>
#!     is encoded by
#!     <M>[ [ [i,i],[i] ], [1,-1] ]</M>.
#!   </Item>
#! </List>
#!
#! Finally, the function adds the relation
#! <M>\sum_i \delta_i - 1 = 0</M>,
#! represented internally as a linear combination of monomials.
#!
#! The output is intended for use in Gröbner basis computations and
#! presentations of Drinfeld doubles.
#!
#! @BeginExampleSession
#! gap> RelationsOfkGdual([9,10,11]);
#! [ ... ]
#! @EndExampleSession
#!
DeclareGlobalFunction( "RelationsOfkGdual" );
#! @Section Transporter Of <M>\Gamma</M> for all <M>i, j\in \mathbb{F}\textsubscript{4}</M>.
#!
#! @Arguments elm1
#! @Returns una función que actúa como la Delta de Kronecker, fijando 
#! el valor de referencia <A>elm1</A> en $\Gamma$.
#! @Description
#! La función devuelta (<A>delta_elm1</A>) toma un argumento <A>elm2</A> y
#! retorna $1$ si <A>elm2</A> es igual al valor de <A>elm1</A> proporcionado,
#! y $0$ en caso contrario. 
#! Formalmente: <A>delta_elm1(elm2)</A> es $1$ si <A>elm1 = elm2</A>,
#! y $0$ caso contrario.
DeclareGlobalFunction( "DeltaFunctionForSDP" );

#! @Section Structure Matrices for Delta Functions
#!
#! @Arguments simpleM
#! @Returns A list of records describing the nonzero actions of delta functions on the simple module <A>simpleM</A>.
#!
#! @Description
#! Computes the action of all delta functions
#! <M>\delta_h \in k^G</M>,
#! where <M>h \in G</M>,
#! on the simple module <A>simpleM</A>.
#!
#! Only nonzero structure matrices are returned.
#!
#! Each entry of the returned list is a record with the fields:
#! <List>
#!   <Item>
#!     <C>element</C>: the group element <M>h</M>;
#!   </Item>
#!   <Item>
#!     <C>conjugationBasis</C>: the list of conjugates
#!       <M>xgx^{-1}</M>
#!       corresponding to the basis of the module;
#!   </Item>
#!   <Item>
#!     <C>matrix</C>: the corresponding structure matrix.
#!   </Item>
#! </List>
#!
#! @BeginExampleSession
#! gap> data := NonzeroDeltaStructureMatrices(simpleM);
#! gap> Length(data);
#! 3
#! gap> data[1].element;
#! (0,3)
#! @EndExampleSession
DeclareGlobalFunction("NonzeroDeltaStructureMatrices");


#! @Arguments simpleM
#! @Returns Nothing.
#!
#! @Description
#! Prints the information returned by
#! <Ref Func="NonzeroDeltaStructureMatrices"/>
#! in a readable format.
#!
#! @BeginExampleSession
#! gap> PrintNonzeroDeltaStructureMatrices(simpleM);
#! Basis conjugation: ...
#! Group element: ...
#! Matrix:
#! ...
#! @EndExampleSession
DeclareGlobalFunction( "PrintNonzeroDeltaStructureMatrices" );
DeclareGlobalFunction( "AttachDeltaStructureMatrices" );
DeclareGlobalFunction( "PrintDeltaStructureMatrices" );
DeclareGlobalFunction( "QGNAG_DeltaMatrixOfElement" );