#! @Chapter Hilbet Series and Characters
#!
#! @Section Hilbet Series
#!
#! @Arguments BasisMod, BasisSubMod, BasisNichols, NicholsGradingData
#!
#! @Returns
#! A list of grading records encoding the Hilbert series coefficients.
#!
#! @Description
#! Given a basis of a module, a basis of a submodule, a basis of a Nichols
#! algebra, and grading data associated to the Nichols algebra, this function
#! computes the graded multiplicities of the submodule elements with respect
#! to the grading induced by the Nichols algebra basis.
#!
#! More precisely, for each element in <A>BasisSubMod</A>, the function:
#! <List>
#!   <Item>
#!     decomposes the element in the basis <A>BasisMod</A>;
#!   </Item>
#!   <Item>
#!     determines the first nonzero basis component;
#!   </Item>
#!   <Item>
#!     identifies the corresponding basis element in
#!     <A>BasisNichols</A>;
#!   </Item>
#!   <Item>
#!     computes its degree;
#!   </Item>
#!   <Item>
#!     matches this degree with the corresponding grading record in
#!     <A>NicholsGradingData</A>.
#!   </Item>
#! </List>
#!
#! The output is a list of records of the form
#! <C>rec( graded_i := i, count := n )</C>,
#! where <C>count</C> is the number of basis elements of the submodule
#! having degree <C>i</C>.
#!
#! @BeginExample
#! gap> HS := QGNAG_HSData(
#! >     Basis(L),
#! >     Basis(S),
#! >     BasisNichols,
#! >     NicholsGradingData
#! > );
#! [ rec( graded_i := 0, count := 1 ),
#!   rec( graded_i := 1, count := 4 ),
#!   rec( graded_i := 2, count := 6 ) ]
#!
#! @EndExample
DeclareGlobalFunction( "QGNAG_HSData" );
#! @Section Character
#!
#! @Arguments L, Simple, BasisNichols, NicholsGradingData
#!
#! @Returns
#! A record containing the Hilbert series coefficients, the socle
#! generated by the highest-weight vectors, and a decomposition of
#! its basis according to the Nichols grading.
#!
#! @Description
#! Let <A>L</A> be a module and let <A>Simple</A> be a simple module
#! whose basis determines a family of highest-weight vectors inside
#! <A>L</A>.
#!
#! The function constructs the submodule generated by these
#! highest-weight vectors and computes its graded structure with
#! respect to the Nichols algebra basis <A>BasisNichols</A>.
#!
#! More precisely, the function:
#! <List>
#!   <Item>
#!     constructs the submodule generated by the highest-weight
#!     vectors associated with <A>Simple</A>;
#!   </Item>
#!   <Item>
#!     computes a basis of this submodule;
#!   </Item>
#!   <Item>
#!     determines the Nichols degree of each basis vector;
#!   </Item>
#!   <Item>
#!     counts the multiplicities in each degree;
#!   </Item>
#!   <Item>
#!     groups basis vectors according to their degree.
#!   </Item>
#! </List>
#!
#! The grading is determined from <A>BasisNichols</A>, while the
#! admissible degrees are specified by
#! <A>NicholsGradingData</A>.
#!
#! The resulting record contains:
#! <List>
#!   <Item>
#!     <C>HScoeffs</C>: Hilbert series coefficients;
#!   </Item>
#!   <Item>
#!     <C>Socle</C>: the generated submodule;
#!   </Item>
#!   <Item>
#!     <C>GradedBasis</C>: a record whose entries contain the basis
#!     vectors grouped by degree.
#!   </Item>
#! </List>
#!
#! Mathematically, if
#! <M>S \subseteq L</M>
#! denotes the generated submodule, the function computes the graded
#! decomposition
#! <M>
#! S=\bigoplus_{i\geq 0} S_i
#! </M>
#! and records the dimensions
#! <M>\dim(S_i)</M>.
#!
#! These dimensions are precisely the coefficients of the Hilbert
#! series
#! <M>
#! H_S(t)=\sum_{i\geq 0}\dim(S_i)t^i.
#! </M>
#!
#! @BeginExample
#! gap> charData :=
#! >     QGNAG_Character(
#! >         L,
#! >         Simple,
#! >         BasisNichols,
#! >         NicholsGradingData
#! >     );
#!
#! gap> charData.HScoeffs;
#! [ rec( graded_i := 0, count := 1 ),
#!   rec( graded_i := 1, count := 2 ),
#!   rec( graded_i := 2, count := 1 ) ]
#!
#! gap> charData.GradedBasis.("1");
#! [ v1, v2 ]
#!
#! @EndExample
#!
DeclareGlobalFunction( "QGNAG_Character" );
#!
#! @Arguments HScoeffs
#!
#! @Returns
#! Nothing. The function only prints the Hilbert series.
#!
#! @Description
#! Prints the Hilbert series associated to a graded object from a list
#! of grading coefficients.
#!
#! The input <A>HScoeffs</A> must be a list of records of the form
#! <C>rec( graded_i := i, count := n )</C>, where:
#! <List>
#!   <Item>
#!     <C>graded_i</C> denotes the degree;
#!   </Item>
#!   <Item>
#!     <C>count</C> denotes the multiplicity in that degree.
#!   </Item>
#! </List>
#!
#! The function constructs a polynomial expression
#! $H(t) = \sum_i a_i t^i$
#! and prints it in a human-readable form.
#!
#! Terms with zero coefficient are omitted.
#! If the coefficient is equal to <C>1</C>, the coefficient is not printed.
#!
#! @BeginExample
#! gap> HS := [
#! >     rec( graded_i := 0, count := 1 ),
#! >     rec( graded_i := 1, count := 4 ),
#! >     rec( graded_i := 2, count := 6 )
#! > ];
#! gap> QGNAG_PrintHS(HS);
#! Hilbert Serie: H(t) = t^0 + 4t^1 + 6t^2.
#!
#! @EndExample
DeclareGlobalFunction( "QGNAG_PrintHS" );

