#! @Chapter Homomorphism Spaces
#!
#! This chapter contains routines for computing dimensions of
#! homomorphism spaces between finite-dimensional representations.
#!
#! @Section A quantum group at the symmetric group
#!
#! Let
#! $$
#! \mathcal{G}=
#! \{X_0,X_1,X_2,
#!   M_s,M_t,
#!   D_e,D_{(12)},D_{(123)},D_{(13)},D_{(132)},D_{(23)},
#!   Y_0,Y_1,Y_2\}
#! $$
#! be the collection of matrices representing the generators of the
#! Drinfeld double $\mathcal{D}(\mathcal{FK}_3\#\Bbbk\mathbb{S}_3)$. The following list stores these matrices in the
#! order used throughout the example.
#!
#! @BeginExample
#! all_matrix_rep := [
#!     X0_matrix,
#!     X1_matrix,
#!     X2_matrix,
#!     Ms_matrix,
#!     Mt_matrix,
#!     De_matrix,
#!     D12_matrix,
#!     D123_matrix,
#!     D13_matrix,
#!     D132_matrix,
#!     D23_matrix,
#!     Y0_matrix,
#!     Y1_matrix,
#!     Y2_matrix
#! ];
#! @EndExample
#!
#!
#! We first define the ground field. Throughout this example we work
#! over the cyclotomic field of order six.
#!
#! @BeginExample
#! F := CF(6);
#! @EndExample
#!
#! The matrices introduced above define a representation of the Hopf
#! algebra generators. The algebra generated by these matrices inside
#! the full matrix algebra over $\mathbb{F}$ is constructed as follows.
#!
#! @BeginExample
#! D := AlgebraWithOne( F, all_matrix_rep );
#! @EndExample
#!
#! The resulting algebra $\mathfrak{D}$ acts naturally on the vector space
#! $\mathbb{F}^{N\times m}$. This action defines a left  $\mathfrak{D}$-module, which realizes the
#! Verma module associated with the chosen simple $\mathcal{D}(G)$-module $M$.
#!
#! @BeginExample
#! L := LeftAlgebraModule( D, \*, F^Nm );
#! @EndExample
#!
#! Inside the Verma module there is a distinguished copy of the simple
#! module from which the induction process starts. The following command
#! extracts the submodule generated by the basis vectors corresponding
#! to this embedded simple module.
#!
#! More precisely, if $B$ denotes the basis of the Nichols algebra and
#! $\{v_1,\ldots,v_m\}$ is a basis of the simple $\mathcal{D}(G)$-module $M$, then the vectors
#! $$ 
#! x_{top} \otimes v_1,\ldots, x_{top}\otimes v_m
#! $$
#! are selected inside the basis of the Verma module and used to generate
#! the corresponding submodule.
#!
#! @BeginExample
#! S := SubAlgebraModule(
#!     L,
#!     List(
#!         [1..Length(simpleM.base)],
#!         i -> BasisVectors(Basis(L))[Length(Base_FK3) * i]
#!     )
#! );
#! @EndExample
#!
#! The Nichols algebra is naturally $\mathbb{N}_{0}$-graded. The following
#! record specifies the dimensions of its homogeneous components.
#!
#! More precisely, the entry
#! `rec( graded_i := d, dimBi := n )`
#! indicates that the homogeneous component of Nichols degree $d$
#! has dimension $n$.
#!
#! In the present example the Nichols algebra has Hilbert polynomial
#! $$
#! H_{\mathfrak{B}(V)}(t) = 1 + 3t + 4t^2 + 3t^3 + t^4,
#! $$
#! and therefore its homogeneous components have dimensions
#! $1,3,4,3,1$ in degrees $0,1,2,3,4$, respectively.
#!
#! @BeginExample
#! NicholsGradingData := [
#!     rec( graded_i := 0, dimBi := 1 ),
#!     rec( graded_i := 1, dimBi := 3 ),
#!     rec( graded_i := 2, dimBi := 4 ),
#!     rec( graded_i := 3, dimBi := 3 ),
#!     rec( graded_i := 4, dimBi := 1 )
#! ];
#! @EndExample
#!
#! Using the grading information together with the Verma module $L$,
#! the simple module `simpleM`, and the Nichols algebra basis
#! `Base_FK3`, we compute the graded structure of the Verma module.
#!
#! The function <Ref Func="QGNAG_Character"/> determines:
#! <List>
#!   <Item>
#!     a homogeneous basis for each Nichols degree;
#!   </Item>
#!   <Item>
#!     the multiplicities occurring in every homogeneous component;
#!   </Item>
#!   <Item>
#!     the socle of the module.
#!   </Item>
#! </List>
#!
#! @BeginExample
#! verma_char := QGNAG_Character(
#!     L,
#!     simpleM,
#!     Base_FK3,
#!     NicholsGradingData
#! );
#! @EndExample
#!
#! The resulting record contains three components:
#! <List>
#!   <Item>
#!     `GradedBasis`, storing basis vectors grouped by degree;
#!   </Item>
#!   <Item>
#!     `HScoeffs`, storing the coefficients of the Hilbert series;
#!   </Item>
#!   <Item>
#!     `Socle`, containing the socle of the module.
#!   </Item>
#! </List>
#!
#! In this example the homogeneous components of degrees $0$ and $1$
#! vanish, while the dimensions of the nonzero components are
#! $3$, $4$, and $3$ in degrees $2$, $3$, and $4$, respectively.
#!
#! The Hilbert polynomial can be displayed using
#! <Ref Func="QGNAG_PrintHS"/>.
#!
#! @BeginExample
#! QGNAG_PrintHS( verma_char );
#! Hilbert polynomial: H(t) = 3t^2 + 4t^3 + 3t^4.
#! @EndExample
#!
#! This shows that the socle identified by
#! `verma_char.Socle` is a graded module concentrated in
#! Nichols degrees $2$, $3$, and $4$. The corresponding homogeneous
#! decomposition is
#! $$
#! S = S_2 \oplus S_3 \oplus S_4,
#! $$
#! where
#! $$
#! \dim(S_2)=3,\qquad
#! \dim(S_3)=4,\qquad
#! \dim(S_4)=3.
#! $$
#! In particular,
#! $$
#! \dim(S)=3+4+3=10.
#! $$
#!
#! @BeginExample
#! Sum( List( verma_char.HScoeffs, x -> x.count ) );
#! 10
#! @EndExample
#! The component `GradedBasis` stores explicit bases for each
#! homogeneous subspace $S_i$.
#!
#! We now study the action of the dual group-algebra generator
#! $D_{(12)}$ on the homogeneous component of Nichols degree $2$ of the
#! graded socle.
#!
#! The basis vectors spanning this homogeneous component are extracted
#! from the graded decomposition computed previously.
#!
#! @BeginExample
#! deg_2_vectors := verma_char.GradedBasis.("2");
#! @EndExample
#!
#! The underlying field is obtained from the left action domain of the
#! socle module. Using the vectors of degree $2$, we construct the
#! corresponding homogeneous subspace.
#!
#! @BeginExample
#! fieldS        := LeftActingDomain( S );
#! deg_2_V  := VectorSpace( fieldS, deg_2_vectors );
#! deg_2_B  := Basis( deg_2_V, deg_2_vectors );
#! @EndExample
#!
#! Since the homogeneous component is stable under the action of the
#! generators of the Drinfeld double, it is natural to study the
#! restriction of the action of $D_{(12)}$ to this subspace.
#!
#! The following command computes the matrix of the linear
#! transformation induced by $D_{(12)}$ with respect to the chosen basis.
#!
#! @BeginExample
#! D12_deg_2_mat := MatrixOfAction( deg_2_B, D12_matrix );
#! @EndExample
#!
#! Equivalently, one may compute the coordinate vector of
#! $vD_{(12)}$ for each basis vector $v$ and assemble the resulting
#! coefficients into a matrix.
#!
#! @BeginExample
#! D12_deg_2_coeffs := List( deg_2_B, v -> Coefficients( deg_2_B, v * D12_matrix ) );;
#! D12_deg_2_mat_alt := TransposedMat( D12_deg_2_coeffs );
#! @EndExample
#!
#! Both constructions produce the same matrix representation of the
#! restricted action of $D_{12}$.
#!
#! @BeginExample
#! D12_degree_two_matrix;
#! [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ]
#! D12_degree_two_matrix_alt;
#! [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ]
#! @EndExample
#!
#! The agreement of these two computations provides an explicit
#! verification that the matrix returned by `MatrixOfAction`
#! coincides with the matrix obtained directly from the action on basis
#! vectors.
#!
# In particular, with respect to the chosen homogeneous basis of
# degree $2$, the generator $D_{12}$ acts as the projection onto the
# one-dimensional subspace generated by the second basis vector.
#
# Indeed, if
# $$
# \mathcal{B}_2=\{b_1,b_2,b_3\},
# $$
# denotes the chosen basis of the degree-$2$ component, then
# $$
# b_1D_{12}=0,
# \qquad
# b_2D_{12}=b_2,
# \qquad
# b_3D_{12}=0.
# $$
# Consequently, the eigenspaces of the restricted action are
# $$
# E_1=\langle b_2\rangle
# $$
# and
# $$
# E_0=\langle b_1,b_3\rangle,
# $$
# showing that the degree-$2$ homogeneous component decomposes as a
# direct sum of a one-dimensional $D_{12}$-invariant subspace and a
# two-dimensional kernel.
#!
#! @Section Build Generator Matrices
#!
#! @Arguments simple, allPairsInG, actionMatrices
#!
#! @Returns
#! A list of records describing the action of the group generators on
#! the simple module.
#!
#! @Description
#! Let <M>g_1,\ldots,g_r</M> be the generators of the group associated with the simple module.
#!
#! The input <A>actionMatrices</A> must be a list containing the action
#! matrices associated with these generators.
#!
#! The function constructs a list of records, one for each generator.
#!
#! Each record contains:
#! <List>
#!   <Item>
#!     the corresponding element of <M>G</M>;
#!   </Item>
#!   <Item>
#!     the matrix of the generator acting on the simple module;
#!   </Item>
#!   <Item>
#!     the matrix describing the action on the Nichols basis;
#!   </Item>
#!   <Item>
#!     the weight attached to the simple module.
#!   </Item>
#! </List>
#!
#! The resulting records are intended to be used as part of the action
#! data of the Drinfeld double.
#!
#! @BeginExample
#! gap> gens :=
#! >     QGNAG_BuildGeneratorMatrices(
#! >         simple,
#! >         allPairsInG,
#! >         [Ms_matrix, Mt_matrix]
#! >     );
#!
#! gap> gens[1].g;
#! ( 0, 1 )
#!
#! @EndExample
#!
DeclareGlobalFunction( "QGNAG_BuildGeneratorMatrices" );
#! @Section Delta Action Matrices
#!
#! @Arguments simple, BaseNichols
#!
#! @Returns
#! A list of records describing the action of the nonzero delta
#! functions <M>\delta_g</M> on the simple module.
#!
#! @Description
#! Let <M>\delta_g \in \Bbbk^G</M>
#! denote the delta function associated with an element <M>g \in G</M>.
#! For every element of <M>G</M>, the function computes:
#! <List>
#!   <Item>
#!     the structure matrix of <M>\delta_g</M> on the simple module;
#!   </Item>
#!   <Item>
#!     the corresponding matrix acting on the Nichols basis;
#!   </Item>
#!   <Item>
#!     the associated group element.
#!   </Item>
#! </List>
#!
#! Records whose structure matrix is zero are removed from the output.
#!
#! Each returned record contains at least the fields
#! <C>g</C>,
#! <C>matrix</C>,
#! and
#! <C>Dg_matrix</C>.
#!
#! The resulting list corresponds precisely to the nontrivial action
#! of the generators of the dual group algebra <M>\Bbbk^G</M>.
#!
#! @BeginExample
#! gap> deltas :=
#! >     QGNAG_DeltaActionMatrices(
#! >         simple,
#! >         BasisFK3
#! >     );
#!
#! gap> deltas[1].g;
#! ( 0, 1 )
#!
#! @EndExample
#!
DeclareGlobalFunction( "QGNAG_DeltaActionMatrices" );
#! @Section Delta Action Matrices
#!
#! @Arguments simple, BaseNichols
#!
#! @Returns
#! A list of records describing the action of the nonzero delta
#! functions <M>\delta_g</M> on the simple module.
#
#! @Description
#! Let <M>\delta_g \in \Bbbk^G</M>
#! denote the delta function associated with an element <M>g \in G</M>.
#! For every element of <M>G</M>, the function computes:
#! <List>
#!   <Item>
#!     the structure matrix of <M>\delta_g</M> on the simple module;
#!   </Item>
#!   <Item>
#!     the corresponding matrix acting on the Nichols basis;
#!   </Item>
#!   <Item>
#!     the associated group element.
#!   </Item>
#! </List>
#!
#! Records whose structure matrix is zero are removed from the output.
#!
#! Each returned record contains at least the fields
#! <C>g</C>, <C>matrix</C>, and <C>Dg_matrix</C>.
#!
#! The resulting list corresponds precisely to the nontrivial action
#! of the generators of the dual group algebra <M>\Bbbk^G</M>.
#!
#! @BeginExample
#! gap> deltas :=
#! >     QGNAG_DeltaActionMatrices(
#! >         simple,
#! >         BasisFK3
#! >     );
#! gap> deltas[1].g;
#! ( 0, 1 )
#! @EndExample
#!
DeclareGlobalFunction( "QGNAG_DGActionMatrices" );
#! @Section QGNAG_MatrixByDegree
#!
#! @Arguments L, verma_char, degree, M_matrix
#!
#! @Returns
#! The matrix describing the action of <A>M_matrix</A> on the
#! homogeneous component of degree <A>degree</A>.
#!
#! @Description
#! Let
#! <M>
#! M=\bigoplus_{d\ge 0} M_d
#! </M>
#! be the graded module encoded by <A>verma_char</A>.
#!
#! The record <A>verma_char</A> must contain a field
#! <C>GradedBasis</C> whose entries store basis vectors grouped by
#! Nichols degree.
#!
#! Given a degree <A>degree</A>, this function:
#! <List>
#!   <Item>
#!     extracts the basis vectors of degree
#!     <M>degree</M>;
#!   </Item>
#!   <Item>
#!     constructs the corresponding homogeneous subspace;
#!   </Item>
#!   <Item>
#!     computes the matrix of the linear transformation
#!     represented by <A>M_matrix</A> on that subspace.
#!   </Item>
#! </List>
#!
#! If no vectors exist in the requested degree, the function returns
#! the empty list.
#!
#! Mathematically, if
#! <M>T</M>
#! denotes the linear operator represented by
#! <A>M_matrix</A>, then the function computes the matrix of
#! <M>T|_{M_d}</M>
#! with respect to the graded basis stored in
#! <A>verma_char</A>.
#!
#! This routine is particularly useful when studying graded
#! characters, homogeneous components, and degree-by-degree actions
#! in Verma modules and related representations.
#!
#! @BeginExample
#! gap> M0 :=
#! >     QGNAG_MatrixByDegree(
#! >         L,
#! >         verma_char,
#! >         0,
#! >         M_matrix
#! >     );
#!
#! gap> M1 :=
#! >     QGNAG_MatrixByDegree(
#! >         L,
#! >         verma_char,
#! >         1,
#! >         M_matrix
#! >     );
#!
#! @EndExample
#!
DeclareGlobalFunction( "QGNAG_MatrixByDegree" );
DeclareGlobalFunction( "QGNAG_MatrixByDegreeAlt" );
#############################################################################
##
#F  QGNAG_GradedActionMatrices( verma_char, Mg_matrix )
##
#! @Arguments verma_char, M_matrix
#!
#! @Returns
#! A record whose entries are indexed by the degrees appearing in
#! <C>verma_char.GradedBasis</C>.
#!
#! @Description
#! Let
#! <M>
#! L=\bigoplus_{d\geq 0} L_d
#! </M>
#! be the graded module encoded by <A>verma_char</A>.
#!
#! For every degree <M>d</M> appearing as a field of
#! <C>verma_char.GradedBasis</C>, this function computes the matrix
#! describing the action of <A>M_matrix</A> on the homogeneous
#! component <M>L_d</M>.
#!
#! More precisely, for each degree string
#! <C>degStr</C> occurring in
#! <C>RecNames( verma_char.GradedBasis )</C>,
#! the function computes
#! <C>
#! QGNAG_MatrixByDegree(
#!     verma_char,
#!     Int( degStr ),
#!     Mg_matrix
#! )
#! </C>
#! whenever the corresponding homogeneous component is nonempty.
#!
#! If the homogeneous component of degree <M>d</M> contains no basis
#! vectors, then the value associated with that degree is the empty list.
#!
#! The result is returned as a record whose fields are the degrees and
#! whose values are the corresponding action matrices.
#!
#! This information is useful for studying graded representations,
#! homogeneous components, graded characters, and spaces of graded
#! module homomorphisms.
#!
#! @BeginExample
#! gap> gradedMatricesMs := QGNAG_GradedActionMatrices( verma_char, Ms_matrix );
#! rec(
#!   0 := [  ],
#!   1 := [  ],
#!   2 := [ [ 0, 0, 1 ], [ 0, -1, 0 ], [ 1, 0, 0 ] ],
#!   3 := [ [ 0, -1, 0, 0 ], [ -1, 0, 0, 0 ],
#!            [ 0, 0, 0, 1 ], [ 0, 0, 1, 0 ] ],
#!   4 := [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ]
#! );
#! gap> gradedMatricesMs.3;
#! [ [ 0, -1, 0, 0 ],
#!   [ -1, 0, 0, 0 ],
#!   [ 0, 0, 0, 1 ],
#!   [ 0, 0, 1, 0 ] ]
#! @EndExample
#!
DeclareGlobalFunction( "QGNAG_GradedActionMatrices" );
#! @Section QGNAG_MatricesByDegree
#!
#! @Arguments L, verma_char, M_matrix
#!
#! @Returns
#! A record whose entries are the matrices describing the action of
#! <A>M_matrix</A> on each homogeneous component of the graded module
#! encoded by <A>verma_char</A>.
#!
#! @Description
#! Let
#! <M>
#! L=\bigoplus_{d\geq 0} L_d
#! </M>
#! be the graded module encoded by the record
#! <A>verma_char</A>.
#!
#! The field <C>GradedBasis</C> of <A>verma_char</A> is assumed to
#! contain basis vectors grouped according to their Nichols degree.
#!
#! For every degree appearing in
#! <C>verma_char.GradedBasis</C>, the function:
#! <List>
#!   <Item>
#!     extracts the corresponding homogeneous basis;
#!   </Item>
#!   <Item>
#!     constructs the associated homogeneous subspace;
#!   </Item>
#!   <Item>
#!     computes the matrix of the action of
#!     <A>M_matrix</A> on that subspace.
#!   </Item>
#! </List>
#!
#! The resulting matrices are stored in a record whose keys are the
#! degree labels.
#!
#! Mathematically, if
#! <M>T</M>
#! denotes the linear operator represented by
#! <A>M_matrix</A>, then the function computes the family
#!
#! <M>
#! \{\,T|_{L_d}\,\}_{d\geq 0},
#! </M>
#!
#! where <M>T|_{L_d}</M> denotes the restriction of
#! <M>T</M> to the homogeneous component of degree
#! <M>d</M>.
#!
#! This function is useful for studying graded actions,
#! graded characters, and block decompositions of modules.
#!
#! @BeginExample
#! gap> gradedMatrices :=
#! >     QGNAG_MatricesByDegree(
#! >         L,
#! >         verma_char,
#! >         Ms_matrix
#! >     );
#!
#! gap> gradedMatrices.("2");
#! [ [ 0, 1, 0, 0 ],
#!   [ 1, 0, 0, 0 ],
#!   [ 0, 0, 1, 0 ],
#!   [ 0, 0, 0, 1 ] ]
#!
#! @EndExample
#!
DeclareGlobalFunction( "QGNAG_MatricesByDegree" );
#! @Section Direct Sum by degree
#!
#! @Arguments verma_char
#!
#! @Returns
#! A block diagonal matrix obtained as the direct sum of all nonempty
#! homogeneous matrices stored in <A>verma_char</A>.
#!
#! @Description
#! The input <A>verma_char</A> is assumed to be a record whose
#! components are degree labels and whose values are matrices.
#!
#! More precisely, the function expects a record of the form
#! <C>
#! rec(
#!     "0" := M0,
#!     "1" := M1,
#!     ...
#! )
#! </C>
#! where each <C>Mi</C> is the matrix describing the action on the
#! homogeneous component of degree <M>i</M>.
#!
#! The function:
#! <List>
#!   <Item>
#!     extracts all degree labels;
#!   </Item>
#!   <Item>
#!     orders them in decreasing degree;
#!   </Item>
#!   <Item>
#!     discards empty matrices;
#!   </Item>
#!   <Item>
#!     computes the block diagonal direct sum of the remaining
#!     matrices.
#!   </Item>
#! </List>
#!
#! Mathematically, if
#! <M>
#! M_d
#! </M>
#! denotes the matrix corresponding to degree
#! <M>d</M>,
#! the function returns
#!
#! <M>
#! M_{d_r}\oplus M_{d_{r-1}}\oplus \cdots \oplus M_{d_1},
#! </M>
#!
#! where
#! <M>
#! d_r > d_{r-1} > \cdots > d_1
#! </M>
#! are the degrees for which the corresponding matrices are nonempty.
#!
#! This construction is useful when reconstructing the full matrix of
#! an operator from its homogeneous blocks.
#!
#! @BeginExample
#! gap> gradedMatrices := rec(
#! >     "0" := [ [ 1 ] ],
#! >     "1" := [ [ 0, 1 ], [ 1, 0 ] ],
#! >     "2" := [ [ -1 ] ]
#! > );
#!
#! gap> QGNAG_DirectSumByDegree( gradedMatrices );
#! [ [ -1, 0, 0, 0 ],
#!   [  0, 0, 1, 0 ],
#!   [  0, 1, 0, 0 ],
#!   [  0, 0, 0, 1 ] ]
#!
#! @EndExample
#!
DeclareGlobalFunction( "QGNAG_DirectSumByDegree" );
#############################################################################
##
#! @Section AllMatricesByDegree
#!
#! @Arguments verma_char, all_matrix_rep
#!
#! @Returns
#! A list whose $i$-th entry is the result of
#! <Ref Func="QGNAG_MatricesByDegree"/>
#! applied to the matrix <C>all_matrix_rep[i]</C>.
#!
#! Equivalently, the returned value is
#! $$
#! \bigl[
#! \mathtt{QGNAG\_MatricesByDegree}( \mathtt{verma\_char},A_1),
#! \dots,
#! \mathtt{QGNAG\_MatricesByDegree}( \mathtt{verma\_char},A_r)
#! \bigr].
#! $$
#!
#! @Description
#! Let $L$ be a graded Verma module and let
#! $\mathcal{A}=\{A_1,\dots,A_r\}$
#! be a collection of matrices describing the action of algebra generators
#! on $L$.
#! This function computes the matrix representation of every element of
#! <A>all_matrix_rep</A> on each homogeneous component of the graded module
#! determined by <A>verma_char</A>.
#!
#! More precisely, if
#! $L=\bigoplus_{d\geq 0} L_d $
#! is the graded decomposition encoded in <A>verma_char</A>, then for each
#! matrix $A_i$ the function
#! <Ref Func="QGNAG_MatricesByDegree"/>
#! is applied, producing the matrices induced by $A_i$ on the graded
#! pieces $L_d$.
#! This is a convenience function that applies
#! <Ref Func="QGNAG_MatricesByDegree"/>
#! to every matrix in a collection of representation matrices.
#!
#! It is typically used to obtain the graded matrix representations of all
#! generators of a module simultaneously, preserving the ordering of the
#! matrices in <C>all_matrix_rep</C>.
DeclareGlobalFunction( "QGNAG_AllMatricesByDegree" );
#! @Section QGNAG_DimensionHomSpace
#!
#! Let $$ A_t=\rho_M(g_t), \qquad B_t=\rho_N(g_t), \qquad t=1,\ldots,r.$$
#! For each generator $g_t$, define $$T_t(X)=XA_t-B_tX.$$
#! Then
#! $$ \operatorname{Hom}_A(M,N) = \bigcap_{t=1}^{r}\ker(T_t).$$
#! This function computes $$\dim\operatorname{Hom}_A(M,N).$$
#!
#! @Arguments A, B, field
#!
#! A list $A=[A_1,\ldots,A_r]$ of matrices acting on $M$,
#! a list $B=[B_1,\ldots,B_r]$ of matrices acting on $N$,
#! and the common coefficient field.
#!
#! @Returns
#!
#! The dimension of the homomorphism space $$\operatorname{Hom}_A(M,N).$$
#!
#! @Arguments A, B
#!
#! @Description
#! 
#! A and B must be lists of the same length r.
#!
#! The entry A[t] must be an n x n matrix representing the action
#! of the t-th generator on M.
#!
#! The entry B[t] must be an m x m matrix representing the action
#! of the same generator on N.
#!
#! All matrices must be defined over the same field.
#!
DeclareGlobalFunction( "QGNAG_DimensionHomSpace" );
DeclareGlobalFunction( "QGNAG_IsValidMatrixRepresentation" );
#! @Arguments Nrep, Mrep
#! Let
#! $$
#! N_i \in M_n(\Bbbk), \qquad M_i \in M_m(\Bbbk),
#! $$
#! be the matrices describing the action of a common generating set
#! $
#! a_1,\dots,a_r
#! $
#! of an algebra $A$ on two finite-dimensional $A$-modules
#! $N$ and $M$, respectively.
#!
#! The lists <A>Nrep</A> and <A>Mrep</A> must have the same length, and the
#! $i$-th entries must correspond to the action of the same generator.
#!
#! @Returns
#! The dimension of the vector space
#! $$
#! Hom_A(N,M).
#! $$
#!
#! @Description
#!
#! Fix bases of the modules $N$ and $M$. Any linear map
#! $$
#! f : N \longrightarrow M
#! $$
#! is represented by a unique matrix
#! $$
#! X \in M_{m\times n}(k),
#! $$
#! where $n=\dim(N)$ and $m=\dim(M)$.
#!
#! The map $f$ is an $A$-module homomorphism if and only if
#! $$
#! f(a\cdot v)=a\cdot f(v)
#! $$
#! for every $a\in A$ and every $v\in N$.
#!
#! Writing this condition in matrix form for the chosen generators
#! $a_1,\ldots,a_r$ yields
#! $$
#! XN_i=M_iX
#! $$
#! for every $i$.
#!
#! Let
#! $A=(a_{ij})\in M_{m\times n}(\Bbbk)$ and
#! $B=(b_{uv})\in M_{p\times q}(\Bbbk)$.
#! Throughout this package we use the convention
#! $$
#! A\otimes B :=
#! \mathtt{KroneckerProduct}(B,A).
#! $$
#! Thus the tensor product matrix is the block matrix
#! $$
#! A\otimes B=
#! \begin{pmatrix}
#! b_{11}A &amp; \cdots &amp; b_{1q}A\\
#! \vdots  &amp; \ddots &amp; \vdots\\
#! b_{p1}A &amp; \cdots &amp; b_{pq}A
#! \end{pmatrix}
#! \in M_{pm\times qn}(\Bbbk).
#! $$
#! Note that &GAP;'s function <Ref Func="KroneckerProduct" BookName="ref"/> uses the opposite
#! ordering convention. Thus the mathematical tensor product
#! $A\otimes B$ is represented in &GAP; by
#! <Example>
#! KroneckerProduct( B, A );
#! </Example>
#! whenever the chosen basis ordering corresponds to the convention
#! used throughout this package.
#!
#! Let
#! $$
#! X=(x_{ij})\in M_{m\times n}(\Bbbk)
#! $$
#! be the matrix representing a linear map
#! $$
#! f:N\longrightarrow M.
#! $$
#!
#! Denote by
#! $$
#! \operatorname{vec}(X)\in \Bbbk^{mn}
#! $$
#! the column vector obtained by stacking the columns of $X$, namely
#! $$
#! \operatorname{vec}(X)
#! =
#! \begin{pmatrix}
#! x_{11}\\
#! \vdots\\
#! x_{m1}\\
#! x_{12}\\
#! \vdots\\
#! x_{m2}\\
#! \vdots\\
#! x_{mn}
#! \end{pmatrix}.
#! $$
#!
#! Throughout this package, the tensor product of matrices is defined by
#! the convention that the mathematical matrix $A\otimes B$ is represented
#! in &GAP; by <K>KroneckerProduct( B, A )</K>.
#!
#! With this convention one has
#! $$
#! \operatorname{vec}(AXB)
#! =
#! (A\otimes B^{T})
#! \operatorname{vec}(X).
#! $$
#!
#! Consequently,
#! $$
#! \operatorname{vec}(XN_i)
#! =
#! (I_m\otimes N_i^{T})
#! \operatorname{vec}(X),
#! $$
#! and
#! $$
#! \operatorname{vec}(M_iX)
#! =
#! (M_i\otimes I_n)
#! \operatorname{vec}(X).
#! $$
#!
#! Therefore the equations
#! $$
#! XN_i-M_iX=0
#! $$
#! are equivalent to the homogeneous linear system
#! $$
#! \bigl(
#! I_m\otimes N_i^{T}
#! -
#! M_i\otimes I_n
#! \bigr)
#! \operatorname{vec}(X)
#! =
#! 0.
#! $$
#!
#! Stacking these systems for all generators produces a matrix
#! $C$ whose kernel is naturally identified with the space
#! $Hom_A(N,M)$.
#! Consequently,
#! $$
#! \dim Hom_A(N,M)
#! =
#! mn-\operatorname{rank}(C).
#! $$
#!
#! The algorithm consists of the following steps.
#!
#! <List>
#! <Item>
#! Verify that the representations
#! <M>
#! N=(N_1,\ldots,N_r)
#! </M>
#! and
#! <M>
#! M=(M_1,\ldots,M_r)
#! </M>
#! contain the same number of generators.
#! </Item>
#!
#! <Item>
#! Verify that all matrices
#! <M>
#! N_i
#! </M>
#! have the same size
#! <M>
#! n\times n,
#! </M>
#! and that all matrices
#! <M>
#! M_i
#! </M>
#! have the same size
#! <M>
#! m\times m.
#! </M>
#! </Item>
#!
#! <Item>
#! Compute
#! <M>
#! n=\dim(N)
#! </M>
#! and
#! <M>
#! m=\dim(M).
#! </M>
#! </Item>
#!
#! <Item>
#! For each generator
#! <M>
#! (N_i,M_i),
#! </M>
#! construct
#! <M>
#! C_i=
#! \bigl(I_m\otimes N_i^T\bigr)
#! -
#! \bigl(M_i\otimes I_n\bigr).
#! </M>
#! </Item>
#!
#! <Item>
#! Form the matrix
#! <M>
#! C=
#! \begin{pmatrix}
#! C_1\\
#! \vdots\\
#! C_r
#! \end{pmatrix}.
#! </M>
#! </Item>
#!
#! <Item>
#! Compute
#! <M>
#! mn-\operatorname{rank}(C).
#! </M>
#! </Item>
#! </List>
#!
#! The resulting integer equals
#! <M>
#! \dim\operatorname{Hom}_A(N,M).
#! </M>
#!
DeclareGlobalFunction( "QGNAG_DimHomAModules" );
#! @BeginExample
#! gap> all_matrix_rep_DG := [
#! >    # Group Algebra Matrices
#! >    Ms_matrix,
#! >    Mt_matrix,
#! >    # Group Algebra dual Matrices
#! >    De_matrix,
#! >    D12_matrix,
#! >    D123_matrix,
#! >    D13_matrix,
#! >    D132_matrix,
#! >    D23_matrix
#! > ];
#! @EndExample
#!
#! The list <C>all_matrix_rep_DG</C> contains the matrices corresponding
#! to the standard generators of the Drinfeld double $D(\Bbbk S_3)$.
#!
#! The matrices <C>Ms_matrix</C> and <C>Mt_matrix</C> represent the action
#! of the generators $s,t \in S_3$ of the group algebra part $\Bbbk S_3$.
#!
#! The matrices
#! <C>De_matrix</C>,
#! <C>D12_matrix</C>,
#! <C>D123_matrix</C>,
#! <C>D13_matrix</C>,
#! <C>D132_matrix</C>,
#! and
#! <C>D23_matrix</C>
#! represent the action of the basis elements
#! $\delta_e$,
#! $\delta_{(12)}$,
#! $\delta_{(123)}$,
#! $\delta_{(13)}$,
#! $\delta_{(132)}$,
#! and
#! $\delta_{(23)}$
#! of the dual group algebra $\Bbbk^{S_3}$.
#!
#! Since $D(\Bbbk S_3)\cong \Bbbk^{S_3}\# \Bbbk S_3$ is generated as an algebra by
#! $\Bbbk S_3$ and $\Bbbk^{S_3}$, the matrices contained in
#! <C>all_matrix_rep_DG</C> form a complete generating set for the
#! matrix representation of $D(\Bbbk S_3)$.
#############################################################################
##
#F  QGNAG_DGActionMatrices( simple, allPairsInG, basisNichols )
##
#! Computes the matrices describing the action of the generators of the
#! Drinfeld double $\mathcal{D}(G)$ on the simple module <A>simple</A>.
#!
#! The returned list contains records corresponding to:
#! <List>
#!   <Item>
#!     the matrices associated with the generators of the group algebra
#!     part of $\mathcal{D}(G)$;
#!   </Item>
#!   <Item>
#!     the matrices associated with the generators of the dual group
#!     algebra part of $\mathcal{D}(G)$.
#!   </Item>
#! </List>
#!
#! More precisely, the function concatenates the output of
#! <Ref Func="QGNAG_BuildGeneratorMatrices"/>
#! and
#! <Ref Func="QGNAG_DeltaActionMatrices"/>.
#!
#! Each element of the returned list is a record containing, among other
#! information, a field <C>matrix</C> storing the matrix representation
#! of the corresponding generator.
#!
#! This output can be used to compute spaces of module homomorphisms
#! between simple $\mathcal{D}(G)$-modules and homogeneous components of Verma
#! modules.
#!
#! Example
#! The following example computes the dimensions of
#! $\operatorname{Hom}_A(M,L_n)$ for the homogeneous components
#! $L_2$, $L_3$, and $L_4$ of a Verma module:
#! @BeginExample
#! gap> AllMatByDegree := QGNAG_AllMatricesByDegree( verma_char, all_matrix_rep_DG );
#! gap> AllMatricesByDegree2 := List( AllMatByDegree, p -> p.2 );
#! gap> AllMatricesByDegree3 := List( AllMatByDegree, p -> p.3 );
#! gap> AllMatricesByDegree4 := List( AllMatByDegree, p -> p.4 );
#! @EndExample
#! @BeginExample
#! gap> DGActionData := QGNAG_DGActionMatrices( simpleM, allPairsInG, Base_FK3 );
#! gap> AllMatricesDG := List( DGActionData, r -> r.matrix );
#! gap> QGNAG_DimHomAModules( AllMatricesDG, AllMatricesByDegree2 );
#! 1
#! gap> QGNAG_DimHomAModules( AllMatricesDG, AllMatricesByDegree3 );
#! 0
#! gap> QGNAG_DimHomAModules( AllMatricesDG, AllMatricesByDegree4 );
#! 1
#! @EndExample
#!
